name = "synthetic-experimentation-lab"
main = "src/index.js"
compatibility_date = "2026-10-06"

[[d1_databases]]
binding = "DB"
database_name = "synthetic-experimentation-lab"
database_id = "54739874-8aef-4fb7-95bf-dc3df20459ff"
